# Use root/example as user/password credentials
version: '3.1'

services:
  mongo:
    image: mongo:bionic
    restart: unless-stopped
    environment:
     - MONGO_INITDB_ROOT_USERNAME=root
     - MONGO_INITDB_ROOT_PASSWORD=example
     - MONGO_INITDB_DATABASE=tracker
    volumes: 
      - ./mongo-volume:/data/db
    ports:
     - 27017-27019:27017-27019 
  backend:
    image: itrack
    restart: unless-stopped
    ports: 
      - 8080:8080
    depends_on:
      - mongo
